{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.linear_model import LinearRegression\n",
    "import argparse\n",
    "import os\n",
    "import numpy as np\n",
    "from sklearn.metrics import root_mean_squared_error\n",
    "import joblib\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import OneHotEncoder\n",
    "import pandas as pd\n",
    "from azureml.core.run import Run\n",
    "from azureml.data.dataset_factory import TabularDatasetFactory\n",
    "\n",
    "# TODO: Create TabularDataset using TabularDatasetFactory\n",
    "# Data is located at:\n",
    "# \"https://automlsamplenotebookdata.blob.core.windows.net/automl-sample-notebook-data/bankmarketing_train.csv\"\n",
    "\n",
    "ds = TabularDatasetFactory.from_delimited_files(\"https://automlsamplenotebookdata.blob.core.windows.net/automl-sample-notebook-data/bankmarketing_train.csv\")\n",
    "x, y = clean_data(ds)\n",
    "\n",
    "# TODO: Split data into train and test sets.\n",
    "x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=.8)\n",
    "\n",
    "train = pd.concat([x_train, y_train], axis=1)\n",
    "\n",
    "run = Run.get_context()\n",
    "\n",
    "def clean_data(dataset):\n",
    "    dataset.itemset = dataset.itemset.fillna('')\n",
    "\n",
    "    dataset.loc[dataset.itemset == 'wrap around rubber', 'itemset'] = 'Wrap Around Rubber'\n",
    "    dataset.loc[dataset.itemset == 'putty', 'itemset'] = 'PUTTY'\n",
    "    dataset.loc[dataset.itemset == 'Putty', 'itemset'] = 'PUTTY'\n",
    "    dataset.loc[dataset.itemset == 'Putty Hack Glaze', 'itemset'] = 'PUTTY'\n",
    "    dataset.loc[dataset.itemset == 'Wood Beads', 'itemset'] = 'WOOD BEADS'\n",
    "    dataset.loc[dataset.itemset == 'Pressure Plate', 'itemset'] = 'PRESSURE PLATE'\n",
    "    dataset.loc[dataset.itemset == 'Snap Beads', 'itemset'] = 'SNAP BEADS'\n",
    "    dataset.loc[dataset.itemset == 'Wrap Around Rubber', 'itemset'] = 'WRAP AROUND RUBBER'\n",
    "    dataset.loc[dataset.itemset == 'Wrap Around Frame', 'itemset'] = 'WRAP AROUND FRAME'\n",
    "    dataset.loc[dataset.itemset == 'metal', 'itemset'] = 'STEEL BEADS'\n",
    "    dataset.loc[dataset.itemset == 'Silicone', 'itemset'] = 'VINYL BEADS'\n",
    "\n",
    "    dataset.loc[dataset.itemset == 'Aluminum Beads', 'itemset'] = 'OTHER'\n",
    "    dataset.loc[dataset.itemset == 'NO BEADS', 'itemset'] = 'OTHER'\n",
    "    dataset.loc[dataset.itemset == 'PUSH RUBBER', 'itemset'] = 'OTHER'\n",
    "    dataset.loc[dataset.itemset == 'STEEL BEADS', 'itemset'] = 'OTHER'\n",
    "    dataset.loc[dataset.itemset == 'ZIPPER WALL', 'itemset'] = 'OTHER'\n",
    "    \n",
    "    dataset = pd.concat([dataset, pd.get_dummies(dataset['itemset'], prefix='itemset')], axis=1)\n",
    "    dataset = dataset.drop('itemset', axis=1)\n",
    "    \n",
    "    dataset.loc[dataset.leadmechanic == 67, 'leadmechanic'] = 'OTHER'\n",
    "    dataset.loc[dataset.leadmechanic == 69, 'leadmechanic'] = 'OTHER'\n",
    "    dataset.loc[dataset.leadmechanic == 74, 'leadmechanic'] = 'OTHER'\n",
    "    dataset.loc[dataset.leadmechanic == 138, 'leadmechanic'] = 'OTHER'\n",
    "    dataset.loc[dataset.leadmechanic == 269, 'leadmechanic'] = 'OTHER'\n",
    "    dataset.loc[dataset.leadmechanic == 132, 'leadmechanic'] = 'OTHER'\n",
    "    dataset.loc[dataset.leadmechanic == 139, 'leadmechanic'] = 'OTHER'\n",
    "    dataset.loc[dataset.leadmechanic == 137, 'leadmechanic'] = 'OTHER'\n",
    "    \n",
    "    dataset = pd.concat([dataset, pd.get_dummies(dataset['leadmechanic'], prefix='leadmechanic')], axis=1)\n",
    "    dataset = dataset.drop('leadmechanic', axis=1)\n",
    "    \n",
    "    dataset = pd.concat([dataset, pd.get_dummies(dataset['locationtype'], prefix='locationtype')], axis=1)\n",
    "    dataset = dataset.drop('locationtype', axis=1)\n",
    "    \n",
    "    dataset.framemat = dataset.framemat.fillna('')\n",
    "\n",
    "    dataset.loc[dataset.framemat == 'wood', 'framemat'] = 'WOOD'\n",
    "    dataset.loc[dataset.framemat == 'Wood', 'framemat'] = 'WOOD'\n",
    "    dataset.loc[dataset.framemat == 'Aluminum', 'framemat'] = 'ALUMINUM'\n",
    "    dataset.loc[dataset.framemat == 'alum', 'framemat'] = 'ALUMINUM'\n",
    "    dataset.loc[dataset.framemat == '450', 'framemat'] = 'ALUMINUM'\n",
    "    dataset.loc[dataset.framemat == '451', 'framemat'] = 'ALUMINUM'\n",
    "    dataset.loc[dataset.framemat == 'Clear Alum', 'framemat'] = 'ALUMINUM'\n",
    "    dataset.loc[dataset.framemat == 'Metal', 'framemat'] = 'ALUMINUM'\n",
    "    dataset.loc[dataset.framemat == 'METAL', 'framemat'] = 'ALUMINUM'\n",
    "    dataset.loc[dataset.framemat == 'STEEL', 'framemat'] = 'ALUMINUM'\n",
    "    dataset.loc[dataset.framemat == 'STAINLESS STEEL', 'framemat'] = 'ALUMINUM'\n",
    "    dataset.loc[dataset.framemat == 'ALUMIUM', 'framemat'] = 'ALUMINUM'\n",
    "    dataset.loc[dataset.framemat == 'STEEL SASH', 'framemat'] = 'ALUMINUM'\n",
    "    dataset.loc[dataset.framemat == 'Vinyl', 'framemat'] = 'VINYL'\n",
    "    dataset.loc[dataset.framemat == 'VINYL SH', 'framemat'] = 'VINYL'\n",
    "\n",
    "\n",
    "    dataset.loc[dataset.framemat == 'BOTTOM SH', 'framemat'] = 'OTHER'\n",
    "    dataset.loc[dataset.framemat == 'DIVISION BAR', 'framemat'] = 'OTHER'\n",
    "    dataset.loc[dataset.framemat == 'FINTUBE', 'framemat'] = 'OTHER'\n",
    "    dataset.loc[dataset.framemat == 'PELLA', 'framemat'] = 'OTHER'\n",
    "    \n",
    "    dataset = pd.concat([dataset, pd.get_dummies(dataset['framemat'], prefix='framemat')], axis=1)\n",
    "    dataset = dataset.drop('framemat', axis=1)\n",
    "    \n",
    "    dataset.loc[dataset.framefunc == 'Bottom of DH', 'framefunc'] = 'BOTTOM DH'\n",
    "    dataset.loc[dataset.framefunc == 'Bottom of Double Hung', 'framefunc'] = 'BOTTOM DH'\n",
    "    dataset.loc[dataset.framefunc == 'Bottom of SH', 'framefunc'] = 'BOTTOM SH'\n",
    "    dataset.loc[dataset.framefunc == 'Curtainwall', 'framefunc'] = 'CURTAIN WALL'\n",
    "    dataset.loc[dataset.framefunc == 'Fixed', 'framefunc'] = 'FIXED'\n",
    "    dataset.loc[dataset.framefunc == 'Flush Glaze', 'framefunc'] = 'FLUSH GLAZE'\n",
    "    dataset.loc[dataset.framefunc == 'GARAGE DOOR VISION PANEL', 'framefunc'] = 'GARAGE DOOR'\n",
    "    dataset.loc[dataset.framefunc == 'LUG SASH TOP', 'framefunc'] = 'SASH'\n",
    "    dataset.loc[dataset.framefunc == 'LUG SASH', 'framefunc'] = 'SASH'\n",
    "    dataset.loc[dataset.framefunc == 'SASH RAIL', 'framefunc'] = 'SASH'\n",
    "    dataset.loc[dataset.framefunc == 'TOP SASH', 'framefunc'] = 'SASH'\n",
    "    dataset.loc[dataset.framefunc == 'BOTTOM SASH', 'framefunc'] = 'SASH'\n",
    "    dataset.loc[dataset.framefunc == 'Transom', 'framefunc'] = 'TRANSOM'\n",
    "    dataset.loc[dataset.framefunc == 'UPPER HALF OF DOUBLE HUNG', 'framefunc'] = 'TOP DH'\n",
    "    dataset.loc[dataset.framefunc == 'UPPER HALF', 'framefunc'] = 'TOP SH'\n",
    "    dataset.loc[dataset.framefunc == 'STATIONARY', 'framefunc'] = 'FIXED'\n",
    "    dataset.loc[dataset.framefunc == 'UPPER DH', 'framefunc'] = 'TOP DH'\n",
    "    dataset.loc[dataset.framefunc == 'UPPER SH', 'framefunc'] = 'TOP SH'\n",
    "    dataset.loc[dataset.framefunc == 'Slider', 'framefunc'] = 'SLIDER'\n",
    "    dataset.loc[dataset.framefunc == 'Stat Window', 'framefunc'] = 'FIXED'\n",
    "\n",
    "    dataset.loc[dataset.framefunc == '451', 'framefunc'] = 'OTHER'\n",
    "    dataset.loc[dataset.framefunc == 'Door', 'framefunc'] = 'OTHER'\n",
    "    dataset.loc[dataset.framefunc == 'FINTUBE SIDELITE', 'framefunc'] = 'OTHER'\n",
    "    dataset.loc[dataset.framefunc == 'GARAGE DOOR', 'framefunc'] = 'OTHER'\n",
    "    dataset.loc[dataset.framefunc == 'HOPPER WINDOW', 'framefunc'] = 'OTHER'\n",
    "    dataset.loc[dataset.framefunc == 'Hand Rail', 'framefunc'] = 'OTHER'\n",
    "    dataset.loc[dataset.framefunc == 'PICTURE WINDOW', 'framefunc'] = 'OTHER'\n",
    "    dataset.loc[dataset.framefunc == 'SKYLITE', 'framefunc'] = 'OTHER'\n",
    "    dataset.loc[dataset.framefunc == 'STORM DOOR', 'framefunc'] = 'OTHER'\n",
    "    \n",
    "    dataset = pd.concat([dataset, pd.get_dummies(dataset['framefunc'], prefix='framefunc')], axis=1)\n",
    "    dataset = dataset.drop('framefunc', axis=1)\n",
    "    \n",
    "    dataset.LongCarry = dataset.LongCarry.fillna(0)\n",
    "    \n",
    "    dataset = dataset.astype({\"itemset_\": bool,\"itemset_OTHER\": bool,\"itemset_PRESSURE PLATE\": bool,\"itemset_PUTTY\": bool, \"itemset_SCREW BEADS\": bool, \"itemset_SNAP BEADS\": bool,\n",
    "            \"itemset_SNAP BEADS\": bool,\"itemset_VINYL BEADS\": bool, \"itemset_WOOD BEADS\": bool,\"itemset_WRAP AROUND FRAME\": bool,\"itemset_WRAP AROUND RUBBER\": bool, \n",
    "             \"itemset_flush glaze\": bool, \"leadmechanic_6\":bool,\"leadmechanic_11\":bool,\"leadmechanic_62\":bool,\"leadmechanic_90\":bool,\"leadmechanic_118\":bool, \"leadmechanic_211\":bool, \"leadmechanic_228\":bool,\n",
    "             \"leadmechanic_OTHER\":bool, \"locationtype_0\": bool, \"locationtype_1\": bool, \"locationtype_2\": bool, \"locationtype_4\": bool,\n",
    "             \"locationtype_5\": bool, \"locationtype_6\": bool, \"locationtype_7\": bool, \"locationtype_9\": bool, \"locationtype_10\": bool,\n",
    "             \"locationtype_11\": bool, \"locationtype_12\": bool, \"locationtype_13\": bool, \"framemat_\": bool, \"framemat_ALUMINUM\": bool, \"framemat_ANDERSEN\":bool,\n",
    "             \"framemat_SASH RAIL\": bool, \"framemat_VINYL\": bool, \"framemat_WOOD\":bool, \"framemat_OTHER\":bool,\n",
    "             \"framefunc_BOTTOM DH\": bool, \"framefunc_BOTTOM SH\": bool, \"framefunc_CASEMENT\": bool, \"framefunc_CURTAIN WALL\":bool,\n",
    "             \"framefunc_FIXED\": bool, \"framefunc_FLUSH GLAZE\": bool, \"framefunc_OTHER\": bool, \"framefunc_SASH\":bool, \"framefunc_SIDELITE\":bool, \"framefunc_SLIDER\":bool,\n",
    "             \"framefunc_TOP DH\": bool, \"framefunc_TOP SH\": bool, \"framefunc_TRANSOM\": bool, \"LongCarry\": bool})\n",
    "    \n",
    "    heightmax = dataset['heightwholenum'].max()\n",
    "    widthmax = dataset['widthWholeNum'].max()\n",
    "    liftmax = dataset['lift'].max()\n",
    "    \n",
    "    dataset['heightwholenum'] = dataset['heightwholenum']/heightmax\n",
    "    dataset['widthWholeNum'] = dataset['widthWholeNum']/widthmax\n",
    "    dataset['lift'] = dataset['lift']/liftmax\n",
    "    \n",
    "    x = dataset[['heightwholenum','widthWholeNum','lift','LongCarry', 'itemset_','itemset_OTHER',\n",
    "             'itemset_PRESSURE PLATE','itemset_PUTTY','itemset_SCREW BEADS','itemset_SNAP BEADS','itemset_VINYL BEADS',\n",
    "             'itemset_WOOD BEADS','itemset_WRAP AROUND FRAME','itemset_WRAP AROUND RUBBER','itemset_flush glaze',\n",
    "             'leadmechanic_6','leadmechanic_11','leadmechanic_62','leadmechanic_90','leadmechanic_118','leadmechanic_211',\n",
    "             'leadmechanic_228','leadmechanic_OTHER','locationtype_0','locationtype_1','locationtype_2','locationtype_4',\n",
    "             'locationtype_5','locationtype_6','locationtype_7','locationtype_9','locationtype_10','locationtype_11',\n",
    "             'locationtype_12', 'locationtype_13','framemat_','framemat_ALUMINUM','framemat_ANDERSEN','framemat_OTHER','framemat_SASH RAIL',\n",
    "             'framemat_VINYL','framemat_WOOD','framefunc_BOTTOM DH','framefunc_BOTTOM SH','framefunc_CASEMENT','framefunc_CURTAIN WALL',\n",
    "             'framefunc_FIXED','framefunc_FLUSH GLAZE','framefunc_OTHER','framefunc_SASH','framefunc_SIDELITE','framefunc_SLIDER','framefunc_TOP DH',\n",
    "             'framefunc_TOP SH','framefunc_TRANSOM']].values\n",
    "    y = dataset['TotalInstallationTime'].values\n",
    "    \n",
    "    return x,y\n",
    "\n",
    "def main():\n",
    "    # Add arguments to script\n",
    "    parser = argparse.ArgumentParser()\n",
    "\n",
    "    parser.add_argument('--fit_intercept', type=bool, default=True, help=\"Whether to calculate the intercept for this model. If set to False, no intercept will be used in calculations (i.e. data is expected to be centered\")\n",
    "    parser.add_argument('--normalize', type=bool, default=True, help=\"This parameter is ignored when fit_intercept is set to False. If True, the regressors X will be normalized before regression by subtracting the mean and dividing by the l2-norm. If you wish to standardize, please use StandardScaler before calling fit on an estimator with normalize=False.\")\n",
    "\n",
    "    args = parser.parse_args()\n",
    "\n",
    "    run.log(\"Fit Intercept:\", np.bool(args.fit_intercept))\n",
    "    run.log(\"Normalize:\", np.bool(args.normalize))\n",
    "\n",
    "    model = LinearRegression(fit_intercept=args.fit_intercept, normalize=args.normalize).fit(x_train, y_train)\n",
    "\n",
    "    rmse = model.score(x_test, y_test)\n",
    "    run.log(\"RMSE\", np.float(rmse))\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
